apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: react-frontend
        image: 483216680875.dkr.ecr.us-east-1.amazonaws.com/frontend-p:latest
          #imagePullPolicy: Never
        ports:
        - containerPort: 3000